### ISSUE TITLE
'EncodedData' does not conform to expected type 'Sequence'

### ISSUE THREAD

**Issue by jdrobert** [stickytools/sticky-encoding#10]
When trying to save `EncodedData` to a file I get the following error.  

`Argument type 'EncodedData' does not conform to expected type 'Sequence'`

This is the code I'm using:

```Swift
let encoder = BinaryEncoder()
if let encoded = try? encoder.encode([String]()) {
  FileManager.default.createFile(atPath: "export.bin", contents: Data(encoded))
}
```

I see the same result in both an iOS project and a Linux project. Any help would be appreciated.

**Comment by jdrobert** [comment]
I see my issue. You don't have a tag for beta 3 so CocoaPods/SPM don't see the latest changes, I'll pull directly from master.

**Comment by tonystone** [comment]
@jdrobert 👍 Let us know if that does not fix it.  If it does not, I'll take a look.

**Comment by tonystone** [comment]
@jdrobert Update: I created a tag for 1.0.0-beta.3 and also released it to CocoaPods.
